services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - ${DATA}/adguardhome/workdir:/opt/adguardhome/work
      - ${DATA}/adguardhome/confdir:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/udp"
      - "443:443/udp"
      - "3000:3000/tcp"
      - "853:853/tcp"
      - "853:853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
      - "6060:6060/tcp"

  cs2-server:
    image: joedwards32/cs2
    container_name: cs2-dedicated
    environment:
      # Server configuration
      SRCDS_TOKEN: ${SRCDS_TOKEN} # Game Server Token from https://steamcommunity.com/dev/managegameservers
      STEAMAPPVALIDATE: 0 # (0 - no validation, 1 - enable validation)
      CS2_SERVERNAME: "changeme" # (Set the visible name for your private server)
      CS2_CHEATS: 0 # (0 - disable cheats, 1 - enable cheats)
      CS2_PORT: 27015 # (CS2 server listen port tcp_udp)
      CS2_SERVER_HIBERNATE: 0 # (Put server in a low CPU state when there are no players. 0 - hibernation disabled, 1 - hibernation enabled)
      CS2_RCON_PORT: null # (Optional, use a simple TCP proxy to have RCON listen on an alternative port. Useful for services like AWS Fargate which do not support mixed protocol ports.)
      CS2_LAN: 0 # (0 - LAN mode disabled, 1 - LAN Mode enabled)
      CS2_RCONPW: ${CS2_RCONPW} # (RCON password)
      CS2_PW: ${CS2_PW} # (CS2 server password)
      CS2_MAXPLAYERS: 10 # (Max players)
      CS2_ADDITIONAL_ARGS: null # (Optional additional arguments to pass into cs2)
      CS2_CFG_URL: null # HTTP/HTTPS URL to fetch a Tar Gzip bundle of configuration files/mods
      # Game modes
      CS2_GAMEALIAS: null # (Game type, e.g. casual, competitive, deathmatch. See https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      CS2_GAMETYPE: 0 # (Used if CS2_GAMEALIAS not defined. See https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      CS2_GAMEMODE: 1 # (Used if CS2_GAMEALIAS not defined. See https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      CS2_MAPGROUP: "mg_active" # (Map pool)
      CS2_STARTMAP: "de_inferno" # (Start map)
      # Bots
      CS2_BOT_DIFFICULTY: null # (0 - easy, 1 - normal, 2 - hard, 3 - expert)
      CS2_BOT_QUOTA: null # (Number of bots)
      CS2_BOT_QUOTA_MODE: null # (fill, competitive)
      # TV
      TV_AUTORECORD: 0 # Automatically records all games as CSTV demos: 0=off, 1=on.
      TV_ENABLE: 0 # Activates CSTV on server: 0=off, 1=on.
      TV_PORT: 27020 # Host SourceTV port
      TV_PW: ${TV_PW} # CSTV password for clients
      TV_RELAY_PW: ${TV_RELAY_PW} # CSTV password for relay proxies
      TV_MAXRATE: 0 # World snapshots to broadcast per second. Affects camera tickrate.
      TV_DELAY: 0 # Max CSTV spectator bandwidth rate allowed, 0 == unlimited
      # Logs
      CS2_LOG: "on" # 'on'/'off'
      CS2_LOG_MONEY: 0 # Turns money logging on/off: (0=off, 1=on)
      CS2_LOG_DETAIL: 0 # Combat damage logging: (0=disabled, 1=enemy, 2=friendly, 3=all)
      CS2_LOG_ITEMS: 0 # Turns item logging on/off: (0=off, 1=on)
    volumes:
      - cs2:/home/steam/cs2-dedicated/ # Persistent data volume mount point inside container
    ports:
      - "27015:27015/tcp" # TCP
      - "27015:27015/udp" # UDP
      - "27020:27020/udp" # UDP

  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - homer:/www/assets
    user: "1000:1000" # default
    environment:
      INIT_ASSETS: 1 # default

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    volumes:
      - ${DATA}/jellyfin/config:/config
      - ${DATA}/jellyfin/cache:/cache
      - /media:/media
    network_mode: host
    restart: unless-stopped

  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "36676:25565"
    environment:
      EULA: true
      MOTD: "§l§aWeekly Games§r §9Discord§r Minecraft §o§c%VERSION%§r server running §o§c%TYPE%§r."
      DIFFICULTY: "hard"
      OPS: |
        DanteVB
        Otakeb
        Heruth99
      ICON: "https://cdn.discordapp.com/icons/1132409092917440644/b5d41a2889dcd44fc0d83f4522ab15ed.webp"
      OVERRIDE_ICON: true
      ENABLE_QUERY: true
      ENABLE_COMMAND_BLOCK: true
      VIEW_DISTANCE: 32
      MEMORY: 8G
      TYPE: "Paper"
    volumes:
      - minecraft-server:/data
  
  creative-minecraft-server:
    image: itzg/minecraft-server
    container_name: creative-minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "36677:25565"
    environment:
      EULA: true
      MODE: "creative"
      ALLOW_FLIGHT: true
      MOTD: "§l§aWeekly Games§r §9Discord§r Minecraft §o§c%VERSION%§r server running §o§c%TYPE%§r."
      DIFFICULTY: "hard"
      OPS: |
        DanteVB
        Otakeb
        Heruth99
      ICON: "https://cdn.discordapp.com/icons/1132409092917440644/b5d41a2889dcd44fc0d83f4522ab15ed.webp"
      OVERRIDE_ICON: true
      ENABLE_QUERY: true
      ENABLE_COMMAND_BLOCK: true
      VIEW_DISTANCE: 32
      MEMORY: 8G
      TYPE: "Paper"
      TZ: ${TZ}
    volumes:
      - creative-minecraft-server:/data

  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    ports:
      # - 80:80 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8080:8080
      # - 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    environment: # Is needed when using any of the options below
      # - AIO_DISABLE_BACKUP_SECTION=false # Setting this to true allows to hide the backup section in the AIO interface. See https://github.com/nextcloud/all-in-one#how-to-disable-the-backup-section
      - APACHE_PORT=11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - APACHE_IP_BINDING=127.0.0.1 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # - BORG_RETENTION_POLICY=--keep-within=7d --keep-weekly=4 --keep-monthly=6 # Allows to adjust borgs retention policy. See https://github.com/nextcloud/all-in-one#how-to-adjust-borgs-retention-policy
      # - COLLABORA_SECCOMP_DISABLED=false # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
      # - NEXTCLOUD_DATADIR=/mnt/ncdata # Allows to set the host directory for Nextcloud's datadir. ⚠️⚠️⚠️ Warning: do not set or adjust this value after the initial Nextcloud installation is done! See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      # - NEXTCLOUD_MOUNT=/mnt/ # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      # - NEXTCLOUD_UPLOAD_LIMIT=10G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      # - NEXTCLOUD_MAX_TIME=3600 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      # - NEXTCLOUD_MEMORY_LIMIT=512M # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud
      # - NEXTCLOUD_TRUSTED_CACERTS_DIR=/path/to/my/cacerts # CA certificates in this directory will be trusted by the OS of the nexcloud container (Useful e.g. for LDAPS) See See https://github.com/nextcloud/all-in-one#how-to-trust-user-defined-certification-authorities-ca
      # - NEXTCLOUD_STARTUP_APPS=deck twofactor_totp tasks calendar contacts notes # Allows to modify the Nextcloud apps that are installed on starting AIO the first time. See https://github.com/nextcloud/all-in-one#how-to-change-the-nextcloud-apps-that-are-installed-on-the-first-startup
      # - NEXTCLOUD_ADDITIONAL_APKS=imagemagick # This allows to add additional packages to the Nextcloud container permanently. Default is imagemagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container
      # - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick # This allows to add additional php extensions to the Nextcloud container permanently. Default is imagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-php-extensions-permanently-to-the-nextcloud-container
      # - NEXTCLOUD_ENABLE_DRI_DEVICE=true # This allows to enable the /dev/dri device in the Nextcloud container. ⚠️⚠️⚠️ Warning: this only works if the '/dev/dri' device is present on the host! If it should not exist on your host, don't set this to true as otherwise the Nextcloud container will fail to start! See https://github.com/nextcloud/all-in-one#how-to-enable-hardware-transcoding-for-nextcloud
      # - NEXTCLOUD_KEEP_DISABLED_APPS=false # Setting this to true will keep Nextcloud apps that are disabled in the AIO interface and not uninstall them if they should be installed. See https://github.com/nextcloud/all-in-one#how-to-keep-disabled-apps
      # - TALK_PORT=3478 # This allows to adjust the port that the talk container is using. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-talk-port
      # - WATCHTOWER_DOCKER_SOCKET_PATH=/var/run/docker.sock # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail. For macos it needs to be '/var/run/docker.sock'
      # networks: # Is needed when you want to create the nextcloud-aio network with ipv6-support using this file, see the network config at the bottom of the file
      # - nextcloud-aio # Is needed when you want to create the nextcloud-aio network with ipv6-support using this file, see the network config at the bottom of the file
      # # Uncomment the following line when using SELinux
      # security_opt: ["label:disable"]

  nginxproxymanager:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ${DATA}/nginxproxymanager/data:/data
      - ${DATA}/nginxproxymanager/letsencrypt:/etc/letsencrypt

  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      CLEANUP: true
      INTERVAL: 300
      LOG_LEVEL: info
      SELF_UPDATE: true
      IGNORE: immich-server immich-microservices immich-machine-learning redis database
      TZ: ${TZ}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - "32400:32400/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      TZ: ${TZ}
      PLEX_CLAIM: ${PLEX_CLAIM}
      ADVERTISE_IP: ${ADVERTISE_IP}
    volumes:
      - ${DATA}/plex/database:/config
      - ${DATA}/plex/transcode/temp:/transcode
      - /media:/data

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
    volumes:
      - ${DATA}/qbittorrent/config:/config
      - ${DATA}/qbittorrent/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
      AUTO_UPDATE: true #optional
      RUN_OPTS: null #optional
    volumes:
      - ${DATA}/jackett/data:/config
      - ${DATA}/jackett/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - ${DATA}/radarr/data:/config
      - ${DATA}/radarr/movies:/movies #optional
      - ${DATA}/radarr/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - ${DATA}/sonarr/data:/config
      - ${DATA}/sonarr/tvseries:/tv #optional
      - ${DATA}/sonarr/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - ${DATA}/lidarr/data:/config
      - ${DATA}/lidarr/music:/music #optional
      - ${DATA}/lidarr/downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped

  openbooks:
    volumes:
      - openbooks:/books
    restart: unless-stopped
    container_name: openbooks
    command: --name my_irc_name --persist
    environment:
      - BASE_PATH=/openbooks/
    image: evanbuss/openbooks:latest

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

volumes:
  cs2:
  homer:
  pgdata:
  model-cache:
  minecraft-server:
  creative-minecraft-server:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work
  openbooks:
  overseerr:
