# aerc main configuration
#
# Only non-default settings are listed here.
# See aerc-config(5) for the full reference.

[compose]
editor=nvim
address-book-cmd=khard email --parsable '%s'

[filters]
text/plain=colorize
text/html=html | colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
.headers=colorize
