# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  # Import auto-detected (non-detected) hardware modules
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  #########################
  # Kernel & initrd modules
  #########################

  # Basic kernel modules for NVMe, USB, LVM, MDADM, etc.
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "mpt3sas" "usbhid" "sd_mod" ];

  # Force inclusion of snapshot support
  boot.initrd.kernelModules = [ "dm-snapshot" ];

  # Auto-assemble MDADM arrays and enable LVM in initrd
  boot.initrd.mdadm.enable = lib.mkDefault true;
  boot.initrd.mdadm.autoScan = lib.mkDefault true;
  boot.initrd.lvm.enable   = lib.mkDefault true;

  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  #########################
  # File Systems
  #########################

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b7f21e0b-df90-479c-a5e6-c4057e982d49";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/27EE-4CFA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/e1d59fde-20a5-4372-a878-309bb816106b";
      fsType = "xfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/cb496c82-8c21-47b0-899b-b4fc4947ad37"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
