#!/usr/bin/env bash
# install-mcp-config.sh — write /etc/openclaw/mcp-clients.json on the Pi.
# Run on a dev machine that has `ssh server` AND `ssh <pi-host>` configured.
# The Pi is firewalled away from the server by design, so this uses the
# dev machine as a trusted middleman — tokens stay in memory / short-lived
# tmpfiles, never stored long-term.
#
# Usage: ./install-mcp-config.sh [pi-ssh-host]    (default host: "pi")
#
# Two secret kinds are shipped:
#   1. Static bearer tokens for the legacy MCP servers (openzim, wikipedia,
#      wikidata, searxng, nominatim, photon, valhalla, elev) — these come
#      from /srv/docker/data/mcp/secrets/MCP_TOKEN_<NAME>, generated by
#      scripts/openclaw-v3-secrets.sh.
#   2. The OpenClaw OIDC client_secret for `tcad`'s OAuth client_credentials
#      grant — this comes from /srv/docker/data/authelia/secrets/
#      openclaw_oidc_secret, set up via docker/docs/MCP-OAUTH.md (Authelia
#      runbook). If this secret doesn't exist yet, the script prints a
#      warning and leaves the placeholder in place so the rest of the
#      config still installs cleanly.
set -euo pipefail

PI_HOST="${1:-pi}"
HERE="$(cd "$(dirname "$0")" && pwd)"
SAMPLE="$HERE/mcp-clients.json.sample"

[ -f "$SAMPLE" ] || { echo "missing sample at $SAMPLE" >&2; exit 1; }

# Fetch all bearer tokens AND the OIDC client_secret in one ssh round-trip.
# (Mapping from sample-key → secret-name lives in the Python block below,
# so we don't need a bash assoc array — keeps us compatible with macOS's
# stock bash 3.2.) The OIDC secret is optional: if the file doesn't exist
# yet we ship a sentinel value so the python step can log a warning.
echo "[1/3] fetching tokens from server…" >&2
TOKENS_TSV=$(ssh server '
  for f in /srv/docker/data/mcp/secrets/MCP_TOKEN_*; do
    name=$(basename "$f" | sed "s/MCP_TOKEN_//")
    printf "BEARER\t%s\t%s\n" "$name" "$(cat "$f")"
  done
  oidc_file=/srv/docker/data/authelia/secrets/openclaw_oidc_secret
  if [ -r "$oidc_file" ]; then
    printf "OIDC_SECRET\topenclaw-mcp\t%s\n" "$(cat "$oidc_file")"
  else
    printf "OIDC_SECRET\topenclaw-mcp\t__MISSING__\n"
  fi
')
[ -n "$TOKENS_TSV" ] || { echo "no tokens returned from server" >&2; exit 1; }

# Build the filled config locally. Python because shell sed + secret values
# + JSON is a recipe for escaping bugs.
echo "[2/3] building config locally…" >&2
FILLED=$(
  TOKENS_TSV="$TOKENS_TSV" SAMPLE="$SAMPLE" python3 - <<'PY'
import json, os, sys

bearer_tokens = {}
oidc_secrets = {}
for line in os.environ['TOKENS_TSV'].strip().splitlines():
    kind, name, value = line.split('\t', 2)
    if kind == 'BEARER':
        bearer_tokens[name] = value
    elif kind == 'OIDC_SECRET':
        oidc_secrets[name] = value

with open(os.environ['SAMPLE']) as f:
    data = json.load(f)

# Static-bearer servers — same mapping as before.
bearer_mapping = {
    'openzim':'OPENZIM','wikipedia':'WIKIPEDIA','wikidata-local':'WIKIDATA',
    'searxng':'SEARXNG','nominatim':'NOMINATIM','photon':'PHOTON',
    'valhalla':'VALHALLA','elev':'ELEV',
}
for key, name in bearer_mapping.items():
    if name not in bearer_tokens:
        raise SystemExit(f"token missing for {name}")
    data['servers'][key]['bearer'] = bearer_tokens[name]

# OAuth servers — currently just `tcad`. Inject the openclaw-mcp client_secret
# from Authelia. If it's missing on the server, log a warning to stderr and
# leave the placeholder (so a partial OAuth setup doesn't block the rest
# of the install — the static bearer for tcad-mcp still works).
secret = oidc_secrets.get('openclaw-mcp')
if secret == '__MISSING__' or not secret:
    print(
        "warn: ${DATA}/authelia/secrets/openclaw_oidc_secret not found on server — "
        "tcad entry will keep its placeholder. Set up Authelia per "
        "docker/docs/MCP-OAUTH.md and rerun this script.",
        file=sys.stderr,
    )
else:
    data['servers']['tcad']['auth']['client_secret'] = secret

# Schema validation: every server must have either `auth` (with required
# fields) or `bearer` (string-or-null for the wikidata-remote case).
required_oauth_fields = {'type', 'token_url', 'client_id', 'client_secret', 'scope', 'audience'}
for key, server in data['servers'].items():
    if 'auth' in server:
        missing = required_oauth_fields - set(server['auth'])
        if missing:
            raise SystemExit(f"server {key!r} auth missing fields: {sorted(missing)}")
        if server['auth']['type'] != 'oauth_client_credentials':
            raise SystemExit(
                f"server {key!r} has unsupported auth.type "
                f"{server['auth']['type']!r} (only oauth_client_credentials "
                "is implemented)"
            )
    elif 'bearer' in server:
        # bearer may be None for unauthenticated upstreams (wikidata-remote)
        if server['bearer'] is not None and not isinstance(server['bearer'], str):
            raise SystemExit(f"server {key!r} bearer must be string or null")
    else:
        raise SystemExit(
            f"server {key!r} has neither `auth` nor `bearer` — invalid"
        )

print(json.dumps(data, indent=2))
PY
)

# Ship to Pi (stdin → /tmp on Pi → sudo install → chown openclaw → remove tmp).
# The Pi's sudo will prompt for password interactively if needed — that's
# why we use -t for a TTY.
echo "[3/3] installing on $PI_HOST (sudo will prompt if needed)…" >&2
echo "$FILLED" | ssh "$PI_HOST" 'cat > /tmp/mcp-clients.json.new && chmod 600 /tmp/mcp-clients.json.new'
ssh -t "$PI_HOST" 'sudo install -d -o root -g root -m 755 /etc/openclaw \
  && sudo install -m 600 -o openclaw -g openclaw /tmp/mcp-clients.json.new /etc/openclaw/mcp-clients.json \
  && rm -f /tmp/mcp-clients.json.new \
  && echo "installed /etc/openclaw/mcp-clients.json (openclaw:openclaw 0600)"'

echo "done. restart openclaw on the Pi to pick up the new config."
